steps:
- name: gcr.io/cloud-builders/docker
  id: pull-static
  waitFor: ['-']
  args:
  - pull
  - gcr.io/$PROJECT_ID/scaife-viewer-static:$BRANCH_NAME
- name: gcr.io/cloud-builders/docker
  id: pull-build
  waitFor: ['-']
  args:
  - pull
  - gcr.io/$PROJECT_ID/scaife-viewer-build:$BRANCH_NAME
- name: gcr.io/cloud-builders/docker
  id: pull
  waitFor:
  - pull-static
  - pull-build
  args:
  - pull
  - gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
- name: gcr.io/cloud-builders/docker
  id: build-static
  waitFor: ['pull-static']
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer-static:$BRANCH_NAME
  - --target
  - static
  - "."
- name: gcr.io/cloud-builders/docker
  id: build-build
  waitFor: ['pull-build']
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer-build:$BRANCH_NAME
  - --target
  - build
  - "."
- name: gcr.io/cloud-builders/docker
  waitFor:
  - build-static
  - build-build
  args:
  - build
  - --cache-from
  - gcr.io/$PROJECT_ID/scaife-viewer-static:$BRANCH_NAME
  - --cache-from
  - gcr.io/$PROJECT_ID/scaife-viewer-build:$BRANCH_NAME
  - --cache-from
  - gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
  - "."
images:
- gcr.io/$PROJECT_ID/scaife-viewer-static:$BRANCH_NAME
- gcr.io/$PROJECT_ID/scaife-viewer-build:$BRANCH_NAME
- gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
- gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
options:
  machineType: N1_HIGHCPU_8
