steps:
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - node:8.9-alpine
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - python:3.6-alpine3.6
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --cache-from
  - gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
  - "."
images:
- gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
- gcr.io/$PROJECT_ID/scaife-viewer:$BRANCH_NAME
